### ISSUE TITLE
Missing the first cycle data.

### ISSUE THREAD

**Issue by Willianflower** [rdbraatz/data-driven-prediction-of-battery-cycle-life-before-capacity-degradation#9]
Hi, I 've downloaded the data file(.m file), but when I overviewed the data content(the struct data structure), I found that the first cycle testing data of any battery was missing. Can anyone give any explanation?
The other thing is why the cycle life is 1 larger than cycles number in data file? 
I'm looking at the paper and no relavant answer for above questions, thanks

**Comment by petermattia** [comment]
The first cycle of the 2017-05-12 dataset is missing - the data collection rate was accidentally too high during the experiment, so we excluded it from the batch. You can access the first cycle data via the csv files if you'd like.
We added 1 to the cycle life in some cases because the final capacity recorded was not below 0.88 Ah.
